mass_contact.settings:
  type: mapping
  label: Settings
  mapping:
    mass_contact_recipient_limit:
      type: integer
    mass_contact_send_with_cron:
      type: integer
    mass_contact_optout_d:
      type: integer
    mass_contact_nodecc_d:
      type: integer
    mass_contact_hourly_threshold:
      type: integer
    mass_contact_character_set:
      type: string
    mass_contact_default_sender_name:
      type: string
    mass_contact_default_sender_email:
      type: string
    mass_contact_category_display:
      type: string
    mass_contact_include_from_name:
      type: integer
    mass_contact_include_to_name:
      type: integer
    mass_contact_bcc_d:
      type: integer
    mass_contact_category_override:
      type: integer
    mass_contact_number_of_attachments:
      type: string
    mass_contact_attachment_location:
      type: string
    mass_contact_html_d:
      type: integer
    mass_contact_message_suffix:
      type: string
    mass_contact_wait_time:
      type: integer
