mass_contact.settings:
  type: mapping
  label: Settings
  mapping:
    form_information:
      type: string
      label: 'Additional form help text'
    recipient_limit:
      type: integer
    send_with_cron:
      type: bool
    optout_d:
      type: integer
    nodecc_d:
      type: integer
    hourly_threshold:
      type: integer
    character_set:
      type: string
    default_sender_name:
      type: string
    default_sender_email:
      type: string
    category_display:
      type: string
    include_from_name:
      type: integer
    include_to_name:
      type: integer
    bcc_d:
      type: integer
    category_override:
      type: integer
    number_of_attachments:
      type: string
    attachment_location:
      type: string
    html_d:
      type: integer
    message_suffix:
      type: string
    wait_time:
      type: integer
