mass_contact.settings:
  type: config_object
  label: 'Mass Contact ettings'
  mapping:
    form_information:
      type: string
      label: 'Additional form help text'
    recipient_limit:
      type: integer
      label: 'Recipient limit'
    send_with_cron:
      type: boolean
      label: 'Send with cron/job queue'
    optout_d:
      type: integer
      label: 'Allow users to opt-out of emails'
    nodecc_d:
      type: boolean
      label: 'Create and archive copy of the email'
    hourly_threshold:
      type: integer
    character_set:
      type: string
    default_sender_name:
      type: string
    default_sender_email:
      type: string
    category_display:
      type: string
    include_from_name:
      type: integer
    include_to_name:
      type: integer
    bcc_d:
      type: boolean
    category_override:
      type: integer
    number_of_attachments:
      type: integer
    attachment_location:
      type: string
    html_d:
      type: integer
    message_suffix:
      type: string
    wait_time:
      type: integer
